version: "3"

services:
  react:
    build:
      context: ./
      dockerfile: ./env/docker/Dockerfile
    container_name: frontend-react
    volumes:
      - .:/react
    ports:
      - 3000:3000
    tty: true
