version: "3"

services:
  react:
    build:
      context: ./
      dockerfile: ./env/docker/Dockerfile
    container_name: sig-react
    volumes:
      - .:/react
    ports:
      - 8080:8080
    tty: true
